---
  detectors:
    IrresponsibleModule:
      enabled: false
  exclude_paths:
    - spec/fixtures/project_info.rb # one-time test fixture creator
    - _snippets
    - app/infrastructure/git/repostore/
  
  directories:
    "app/infrastructure/gateways":
      NestedIterators:
        enabled: false
      UtilityFunction:
        enabled: false

    "app/models/mappers":
      NestedIterators:
        enabled: false
