---

development:
  DB_FILENAME:    app/infrastructure/database/local/dev.db
  TENKSTORE_PATH: app/infrastructure/edgar/10Kstore
  # Application
  APP_HOST: http://localhost:9000
  API_HOST: http://localhost:9001
  SESSION_SECRET: <some secret>

app_test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  TENKSTORE_PATH: app/infrastructure/edgar/10Kstore
  # Application
  APP_HOST: http://localhost:9000
  API_HOST: http://localhost:9001

test:
  DB_FILENAME:    app/infrastructure/database/local/test.db
  TENKSTORE_PATH: app/infrastructure/edgar/10Kstore
  # Application
  APP_HOST: http://localhost:9000
  API_HOST: http://localhost:9001
  SESSION_SECRET: <some secret>

production:
  # Assign DATABASE_URL in production
  TENKSTORE_PATH: app/infrastructure/edgar/10Kstore
  # Application
  APP_HOST: http://url.to.app
  API_HOST: http://localhost:9001
  SESSION_SECRET: <some secret>
