---

development:
  DB_FILENAME:    app/infrastructure/database/local/dev.db
  TENKSTORE_PATH: app/infrastructure/edgar/10Kstore

test:
  DB_FILENAME:    app/infrastructure/database/local/test.db
  TENKSTORE_PATH: app/infrastructure/edgar/10Kstore

production:
  # Assign DATABASE_URL in production
  TENKSTORE_PATH: app/infrastructure/edgar/10Kstore
